config/routes.rb
Rails.application.routes.draw do
  get "messages/create"
  resources :tasks
  resource :session
  resources :passwords, param: :token
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "tasks#index"

  post "messages/create" => "messages#create"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
  attribute :session
  delegate :user, to: :session, allow_nil: true
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :tasks
  has_many :users
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :task

  after_create :broadcast_message

  def broadcast_message
    broadcast_append_to(
      [ task, "messages" ], # This is channel name
      target: "messages", # This is target id of the div
      partial: "messages/message",
      locals: { message: self }
    )
  end
end

app/models/session.rb
class Session < ApplicationRecord
  belongs_to :user
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :group
  has_many :messages, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :sessions, dependent: :destroy
  belongs_to :group, optional: true

  normalizes :email_address, with: ->(e) { e.strip.downcase }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Authentication
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/concerns/authentication.rb
module Authentication
  extend ActiveSupport::Concern

  included do
    before_action :require_authentication
    helper_method :authenticated?
  end

  class_methods do
    def allow_unauthenticated_access(**options)
      skip_before_action :require_authentication, **options
    end
  end

  private
    def authenticated?
      resume_session
    end

    def require_authentication
      resume_session || request_authentication
    end

    def resume_session
      Current.session ||= find_session_by_cookie
    end

    def find_session_by_cookie
      Session.find_by(id: cookies.signed[:session_id]) if cookies.signed[:session_id]
    end

    def request_authentication
      session[:return_to_after_authenticating] = request.url
      redirect_to new_session_path
    end

    def after_authentication_url
      session.delete(:return_to_after_authenticating) || root_url
    end

    def start_new_session_for(user)
      user.sessions.create!(user_agent: request.user_agent, ip_address: request.remote_ip).tap do |session|
        Current.session = session
        cookies.signed.permanent[:session_id] = { value: session.id, httponly: true, same_site: :lax }
      end
    end

    def terminate_session
      Current.session.destroy
      cookies.delete(:session_id)
    end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_task

  def create
    @message = @task.messages.create(message_params)
    @message.user = Current.user
    @message.save

    render json: {}, status: :no_content
  end

  private

  def set_task
    @task ||= Task.find(params[:task_id])
  end

  def message_params
    params.require(:message).permit(:content)
  end
end

app/controllers/passwords_controller.rb
class PasswordsController < ApplicationController
  allow_unauthenticated_access
  before_action :set_user_by_token, only: %i[ edit update ]

  def new
  end

  def create
    if user = User.find_by(email_address: params[:email_address])
      PasswordsMailer.reset(user).deliver_later
    end

    redirect_to new_session_path, notice: "Password reset instructions sent (if user with that email address exists)."
  end

  def edit
  end

  def update
    if @user.update(params.permit(:password, :password_confirmation))
      redirect_to new_session_path, notice: "Password has been reset."
    else
      redirect_to edit_password_path(params[:token]), alert: "Passwords did not match."
    end
  end

  private
    def set_user_by_token
      @user = User.find_by_password_reset_token!(params[:token])
    rescue ActiveSupport::MessageVerifier::InvalidSignature
      redirect_to new_password_path, alert: "Password reset link is invalid or has expired."
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  allow_unauthenticated_access only: %i[ new create ]
  rate_limit to: 10, within: 3.minutes, only: :create, with: -> { redirect_to new_session_url, alert: "Try again later." }

  def new
  end

  def create
    if user = User.authenticate_by(params.permit(:email_address, :password))
      start_new_session_for user
      redirect_to after_authentication_url
    else
      redirect_to new_session_path, alert: "Try another email address or password."
    end
  end

  def destroy
    terminate_session
    redirect_to new_session_path
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: %i[ show edit update destroy ]
  # allow_unauthenticated_access only: [:index]

  # GET /tasks or /tasks.json
  def index
    if Current.user
      @tasks = Current.user.group.tasks
    else
      @tasks = Task.none
    end
  end

  # GET /tasks/1 or /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks or /tasks.json
  def create
    @task = Current.user.group.tasks.new(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to @task, notice: "Task was successfully created." }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1 or /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @task, notice: "Task was successfully updated." }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1 or /tasks/1.json
  def destroy
    @task.destroy!

    respond_to do |format|
      format.html { redirect_to tasks_path, status: :see_other, notice: "Task was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def task_params
      params.expect(task: [ :title, :description ])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= content_for(:title) || "The Life Planner" %></title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="mobile-web-app-capable" content="yes">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= yield :head %>

  <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
  <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

  <link rel="icon" href="/icon.png" type="image/png">
  <link rel="icon" href="/icon.svg" type="image/svg+xml">
  <link rel="apple-touch-icon" href="/icon.png">

  <%# Includes all stylesheet files in app/assets/stylesheets %>
  <%#= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
  <%= stylesheet_link_tag "https://fonts.googleapis.com/css2?family=Inter:wght@400;600&display=swap", "tailwind", "data-turbo-track": "reload" %>

  <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
  <%= javascript_importmap_tags %>
</head>
<body class="h-full bg-gray-900">
<div class="min-h-full">
  <nav class="bg-gray-800 shadow-sm">
    <div class="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
      <div class="flex h-16 justify-between">
        <div class="flex">
          <div class="flex flex-shrink-0 items-center">
            <img class="block h-8 w-auto lg:hidden" src="https://tailwindui.com/plus/img/logos/mark.svg?color=indigo&shade=600" alt="Your Company">
            <img class="hidden h-8 w-auto lg:block" src="https://tailwindui.com/plus/img/logos/mark.svg?color=indigo&shade=600" alt="Your Company">
          </div>
          <div class="hidden sm:-my-px sm:ml-6 sm:flex sm:space-x-8">
            <%= link_to "Tasks", tasks_path, class: "inline-flex items-center border-b-2 border-indigo-400 px-1 pt-1 text-sm font-medium text-gray-100" %>
          </div>
        </div>
        <div class="sm:-my-px sm:ml-6 sm:flex sm:space-x-8">
          <% if Current.user %>
            <%= button_to "Logout", session_path, method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-700 text-gray-100 font-medium hover:bg-gray-600" %>
          <% else %>
            <%= button_to "Login", new_session_path, class: "mt-2 rounded-lg py-3 px-5 bg-gray-700 text-gray-100 font-medium hover:bg-gray-600" %>
          <% end %>
        </div>
      </div>
    </div>
  </nav>

  <div class="py-10">
    <main>
      <div class="mx-auto max-w-7xl">
        <%= yield %>
      </div>
    </main>
  </div>
</div>
</body>
</html>

app/views/messages/_message.html.erb
<div data-controller="task-messages" class="p-4 my-4 border-b border-gray-700">
  <div class="flex justify-between items-start">
    <div class="font-bold text-gray-100">
      <%= message.user.email_address %>
    </div>
    <div class="text-sm text-gray-400">
      <%= time_ago_in_words(message.created_at) %> ago
    </div>
  </div>
  <div class="mt-2 text-gray-300">
    <%= message.content %>
  </div>
</div>

app/views/messages/create.html.erb
<div>
  <h1 class="font-bold text-4xl">Messages#create</h1>
  <p>Find me in app/views/messages/create.html.erb</p>
</div>

app/views/tasks/_form.html.erb
<%= form_with(model: task) do |form| %>
  <% if task.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
        <% task.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_field :description %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/tasks/_task.html.erb
<div id="<%= dom_id task %>" class="bg-gray-800 shadow rounded-lg px-5 py-3 my-4">
  <p class="my-5">
    <strong class="text-lg block font-bold mb-1 text-gray-100">Name:</strong>
    <span class="text-gray-300"><%= task.title %></span>
  </p>

  <p class="my-5">
    <strong class="text-lg block font-bold mb-1 text-gray-100">Description:</strong>
    <span class="text-gray-300"><%= task.description %></span>
  </p>
  <p>
    <%= link_to "Show this task", task, class: "ml-2 rounded-lg py-3 px-5 bg-gray-700 text-gray-100 inline-block font-medium hover:bg-gray-600" %>
  </p>
</div>

app/views/tasks/edit.html.erb
<% content_for :title, "Editing task" %>

<h1>Editing task</h1>

<%= render "form", task: @task %>

<br>

<div>
  <%= link_to "Show this task", @task %> |
  <%= link_to "Back to tasks", tasks_path %>
</div>

app/views/tasks/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-900 mb-5 text-green-300 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <% content_for :title, "Tasks" %>

  <div class="flex justify-between items-center">
    <h1 class="font-extrabold text-4xl text-gray-100">Tasks</h1>
    <%= link_to "New task", new_task_path, class: "rounded-lg py-3 px-5 bg-blue-700 text-white block font-medium hover:bg-blue-600" %>
  </div>


    <h3 class="text-4xl font-extrabold my-4 text-gray-100">In Progress</h3>
    <div id="tasks" class="min-w-full">
      <%= render partial: "tasks/task", collection: @tasks, cached: true %>
    </div>
</div>

app/views/tasks/new.html.erb
<% content_for :title, "New task" %>

<h1>New task</h1>

<%= render "form", task: @task %>

<br>

<div>
  <%= link_to "Back to tasks", tasks_path %>
</div>

app/views/tasks/show.html.erb
<% if notice.present? %>
  <p class="py-2 px-3 bg-green-900 mb-5 text-green-300 font-medium rounded-lg inline-block" id="notice">
    <%= notice %>
  </p>
<% end %>

<h3 class="text-4xl font-extrabold my-4 text-gray-100">Task</h3>
<div class="md:w-2/3 w-full flex">
  <div class="bg-gray-800 shadow rounded-lg px-5 py-3 my-4">
    <h1 class="font-bold text-2xl my-4 text-gray-100">
      <%= @task.title %>
    </h1>

    <p class="my-4 text-gray-300">
      <%= @task.description %>
    </p>

    <%= link_to "Edit this task", edit_task_path(@task), class: "mt-2 rounded-lg py-3 px-5 bg-gray-700 text-gray-100 inline-block font-medium hover:bg-gray-600" %>
    <%= link_to "Back to tasks", tasks_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-700 text-gray-100 inline-block font-medium hover:bg-gray-600" %>
    <div class="inline-block ml-2">
      <%= button_to "Destroy this task", @task, method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-red-700 text-gray-100 font-medium hover:bg-red-600" %>
    </div>
  </div>
</div>

<h3 class="text-4xl font-extrabold my-4 text-gray-100">Messages</h3>
<% puts @task.title, @task.id, @task.messages.count %>
<% unless @task.messages.empty? %>
  <div class="bg-gray-800 shadow rounded-lg px-5 py-3 my-4 mt-8">
    <div class="space-y-4 max-h-96 my-4 overflow-y-auto">
      <div id="messages">
        <%= turbo_stream_from @task, "messages" %>
        <%= render @task.messages %>
      </div>
    </div>
  </div>
<% end %>

<%= form_with model: [@task, Message.new], url: messages_create_path ,class: "mt-4" do |f| %>
  <div class="flex gap-4">
    <%= hidden_field_tag :task_id, @task.id %>
    <%= f.text_area :content,
                    class: "flex-1 min-h-[80px] rounded-lg border-gray-600 bg-gray-700 text-gray-100 shadow-sm focus:border-indigo-400 focus:ring-indigo-400",
                    placeholder: "Type your message..."
    %>

    <%= f.submit "Send",
                 class: "rounded-lg py-3 px-5 bg-blue-700 text-white inline-block font-medium cursor-pointer hover:bg-blue-600"
    %>
  </div>
<% end %>